.. contents:: Table of Contents

General
-------

*This section should be understandable by everybody. It should reflect
the rationale, the features, but should not contains deployment, etc*

.. toctree::
   :maxdepth: 2

   foreword
   vocabulary
   design


User\'s Guide
-------------

*This section should contains how to deploy each system. For the 
LabManager, what options are there available, etc., and how to
connect each component.*


Labmanager administrators
`````````````````````````

.. toctree::
   :maxdepth: 2

   installation
   usage_labmanager_admin
   installation_debug

PLE/LMS/PLE administrators
``````````````````````````

*A document for each supported LMS -e.g. any LTI, Moodle <= 2.1 through plug-in,
Moodle 1.9 through plug-in, .LRN, etc. I would be fine with refering to the
doc of each LMS/CMS/PLE plug-in repository*

.. toctree::
   :maxdepth: 2

   usage_lms_intro
   usage_lms_admin

Remote laboratory administrators
````````````````````````````````

*A document for each supported RLMS, refering to the doc available in
each RLMS repository*

.. toctree::
   :maxdepth: 2

   rlms_admin
   

Instructors
```````````

*A document for instructors: how to download the SCORM objects, where from,
how to edit them, etc.*

.. toctree::
   :maxdepth: 2

   usage_teacher


Developers
----------

*Generic documentation about how to create a new RLMS plug-in, how to 
support a new LMS which does not support LTI, and few little documentation
about the internals of the LabManager*

RLMS developers
```````````````

.. toctree::
   :maxdepth: 2
   



LMS/CMS/PLE developers
``````````````````````

.. toctree::
   :maxdepth: 2


LabManager developers
`````````````````````

.. toctree::
   :maxdepth: 2


